package plugin

import (
	"encoding/json"
	"sort"
	"strings"
	"sync"
)

// i18nLayer — слой перевода одного источника (ядра или плагина)
type i18nLayer struct {
	id    string                       // "core" или ID плагина
	dicts map[string]map[string]string // язык -> ключ -> значение
}

// I18nRegistry — упорядоченный реестр слоёв перевода.
// При сборке слои сливаются в порядке очереди плагинов: поздний слой
// перезаписывает ключи раннего, но удалить чужие ключи невозможно.
type I18nRegistry struct {
	mu      sync.RWMutex
	layers  []*i18nLayer
	index   map[string]*i18nLayer // быстрый поиск слоя по ID
	names   map[string]string     // код языка -> отображаемое имя
	coreEN  []byte                // сырой en.json
	coreRU  []byte                // сырой ru.json
	version uint64                // растет при любых изменениях (для ETag)
}

// NewI18nRegistry создает пустой реестр
func NewI18nRegistry() *I18nRegistry {
	return &I18nRegistry{
		index: make(map[string]*i18nLayer),
		names: make(map[string]string),
	}
}

// SeedCore сохраняет словарь ядра (en.json) для пересидирования при сбросах
func (r *I18nRegistry) SeedCore(enData []byte, ruData []byte) {
	r.mu.Lock()
	defer r.mu.Unlock()

	r.coreEN = append([]byte(nil), enData...)
	r.coreRU = append([]byte(nil), ruData...)
	r.names["en"] = "English"
	r.names["ru"] = "Русский"
	r.bump()
}

// Reset очищает все слои и заново сидирует ядро.
// Вызывается при каждой перезагрузке очереди плагинов.
func (r *I18nRegistry) Reset() {
	r.mu.Lock()
	defer r.mu.Unlock()

	r.layers = nil
	r.index = make(map[string]*i18nLayer)
	r.names = map[string]string{"en": "English", "ru": "Русский"}

	if len(r.coreEN) > 0 {
		ly := r.layerLocked("core")
		r.applyFlatLocked(ly, "en", r.coreEN)
	}
	if len(r.coreRU) > 0 {
		ly := r.layerLocked("core")
		r.applyFlatLocked(ly, "ru", r.coreRU)
	}
	r.bump()
}

// AddStatic заносит словарь из файла плагина i18n/<lang>.json
func (r *I18nRegistry) AddStatic(pluginID, lang string, data []byte) {
	r.mu.Lock()
	defer r.mu.Unlock()

	r.applyFlatLocked(r.layerLocked(pluginID), lang, data)
	r.bump()
}

// Add добавляет одну строку от плагина во время выполнения (goja).
// Пустые значения игнорируются: плагин не может "удалить" чужой перевод.
func (r *I18nRegistry) Add(pluginID, lang, key, value string) {
	if key == "" || value == "" {
		return
	}

	r.mu.Lock()
	defer r.mu.Unlock()

	ly := r.layerLocked(pluginID)
	if ly.dicts[lang] == nil {
		ly.dicts[lang] = make(map[string]string)
	}
	ly.dicts[lang][key] = value
	r.bump()
}

// AddMany добавляет пачку строк от плагина во время выполнения
func (r *I18nRegistry) AddMany(pluginID, lang string, kv map[string]string) {
	r.mu.Lock()
	defer r.mu.Unlock()

	ly := r.layerLocked(pluginID)
	if ly.dicts[lang] == nil {
		ly.dicts[lang] = make(map[string]string)
	}
	for k, v := range kv {
		if k == "" || v == "" {
			continue
		}
		ly.dicts[lang][k] = v
	}
	r.bump()
}

// SetLangName объявляет отображаемое имя языка (например, "Русский")
func (r *I18nRegistry) SetLangName(lang, name string) {
	if lang == "" || name == "" {
		return
	}

	r.mu.Lock()
	defer r.mu.Unlock()

	r.names[lang] = name
	r.bump()
}

// BuildJS собирает итоговый файл i18n.js: словари + рантайм (t, set/get, apply).
// Возвращает байты файла и текущую версию реестра для ETag.
func (r *I18nRegistry) BuildJS() ([]byte, uint64) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	// Сливаем слои строго в порядке очереди: поздний перезаписывает раннего
	merged := make(map[string]map[string]string)
	for _, ly := range r.layers {
		for lang, kv := range ly.dicts {
			if merged[lang] == nil {
				merged[lang] = make(map[string]string)
			}
			for k, v := range kv {
				merged[lang][k] = v
			}
		}
	}

	// Список языков: en первый, остальные по алфавиту
	codes := make([]string, 0, len(merged))
	for c := range merged {
		if c != "en" {
			codes = append(codes, c)
		}
	}
	sort.Strings(codes)
	if _, ok := merged["en"]; ok {
		codes = append([]string{"en"}, codes...)
	}

	// Имена языков: недостающие подставляем кодом
	names := make(map[string]string, len(codes))
	for _, c := range codes {
		if n, ok := r.names[c]; ok {
			names[c] = n
		} else {
			names[c] = c
		}
	}

	var sb strings.Builder
	sb.WriteString("/* Silo i18n — generated by core, do not edit. */\n")
	sb.WriteString("var DICTS = ")
	sb.WriteString(marshalJSSafe(merged))
	sb.WriteString(";\nvar LANG_NAMES = ")
	sb.WriteString(marshalJSSafe(names))
	sb.WriteString(";\nvar CODES = ")
	sb.WriteString(marshalJSSafe(codes))
	sb.WriteString(";\n")
	sb.WriteString(i18nJSRuntime)

	return []byte(sb.String()), r.version
}

// layerLocked возвращает слой источника, создавая его при необходимости.
// Вызывается под заблокированным мьютексом.
func (r *I18nRegistry) layerLocked(id string) *i18nLayer {
	if ly, ok := r.index[id]; ok {
		return ly
	}
	ly := &i18nLayer{id: id, dicts: make(map[string]map[string]string)}
	r.index[id] = ly
	r.layers = append(r.layers, ly)
	return ly
}

// applyFlatLocked разбирает плоский JSON {key: value} в слой указанного языка
func (r *I18nRegistry) applyFlatLocked(ly *i18nLayer, lang string, data []byte) {
	var kv map[string]string
	if err := json.Unmarshal(data, &kv); err != nil {
		return
	}

	if ly.dicts[lang] == nil {
		ly.dicts[lang] = make(map[string]string)
	}
	for k, v := range kv {
		if k == "" || v == "" {
			continue
		}
		ly.dicts[lang][k] = v
	}
}

func (r *I18nRegistry) bump() {
	r.version++
}

// marshalJSSafe сериализует в JSON, безопасный для вставки в <script>:
// экранируем '<' и разделители строк U+2028/U+2029
func marshalJSSafe(v any) string {
	data, err := json.Marshal(v)
	if err != nil {
		return "null"
	}

	s := string(data)
	s = strings.ReplaceAll(s, "<", `\u003c`)
	s = strings.ReplaceAll(s, "\u2028", `\u2028`)
	s = strings.ReplaceAll(s, "\u2029", `\u2029`)
	return s
}

// i18nJSRuntime — браузерный рантайм перевода: выбор языка, localStorage,
// fallback-цепочка и применение строк к DOM через data-i18n атрибуты
const i18nJSRuntime = `
var i18n = (function () {
  var STORE_KEY = 'silo_lang';

  function detect() {
    var nav = (navigator.language || 'en').toLowerCase();
    if (DICTS[nav]) return nav;
    var base = nav.split('-')[0];
    if (DICTS[base]) return base;
    return 'en';
  }

  function get() {
    var saved = null;
    try { saved = localStorage.getItem(STORE_KEY); } catch (e) {}
    if (saved && DICTS[saved]) return saved;
    return detect();
  }

  var current = get();

  function set(code) {
    if (!DICTS[code]) return;
    current = code;
    try { localStorage.setItem(STORE_KEY, code); } catch (e) {}
  }

  // Цепочка fallback: текущий язык -> en -> дефолт из аргумента -> сам ключ
  function t(key, def) {
    var d = DICTS[current];
    if (d && typeof d[key] === 'string') return d[key];
    if (DICTS.en && typeof DICTS.en[key] === 'string') return DICTS.en[key];
    return (typeof def === 'string') ? def : key;
  }

  function langs() {
    return CODES.map(function (c) {
      return { code: c, name: LANG_NAMES[c] || c };
    });
  }

  // apply проставляет строки в DOM: data-i18n (текст) и data-i18n-placeholder
  function apply(root) {
    var scope = root || document;
    var nodes = scope.querySelectorAll('[data-i18n]');
    for (var i = 0; i < nodes.length; i++) {
      nodes[i].textContent = t(nodes[i].getAttribute('data-i18n'));
    }
    var ph = scope.querySelectorAll('[data-i18n-placeholder]');
    for (var j = 0; j < ph.length; j++) {
      ph[j].setAttribute('placeholder', t(ph[j].getAttribute('data-i18n-placeholder')));
    }
  }

  return { t: t, get: get, set: set, langs: langs, apply: apply, dicts: DICTS };
})();
window.i18n = i18n;
`
