server:
    host: 0.0.0.0
    port: 8090
storage:
    data_dir: data
    db_name: torrserver.db
    torrents_dir: torrents
plugins:
    dir: plugins
logging:
    level: debug
    file: ""
auth:
    owner_password: "123"
